In [1]:
print("helloworld")

helloworld


In [2]:
print("rez")

rez


# varaibles

In [6]:
name="rezaul"
age=22
income=9000

In [7]:
print(name)
print(age)
print(income)

rezaul
22
9000


In [9]:
namelist="rezaul","haque"
name list

SyntaxError: invalid syntax (922927664.py, line 2)

### space not allowed

In [10]:
2namelist="rezaul"
2namelist

SyntaxError: invalid decimal literal (1155004107.py, line 1)

#### varaible name should not start with number

In [9]:
n2amelist="rez"
name list

SyntaxError: invalid syntax (541162396.py, line 2)

In [11]:
name="garry"
name="rogger"
print(name)

rogger


In [12]:
x=y=z=10
print(x)

10


In [13]:
print(y)

10


In [14]:
x,y,z=1,2,3
print(x)

1


In [15]:
print(y)

2


In [16]:
name="charles"
print(name)
type(name)

charles


str

In [17]:
x=10
y=10.5
x-y

-0.5

In [18]:
x=10
y="ds"
x-y

TypeError: unsupported operand type(s) for -: 'int' and 'str'

In [19]:
x=10.5
y=10
x-y

0.5

#day 2 

## operators                                                         

### arithmatic operator

In [7]:
first_name="rezaul"
second_name="haque"
full_name=first_name+second_name
full_name

'rezaulhaque'

In [1]:
x=10
y=5
x+y

15

In [2]:
x=10
y=5
z=x+y
z

15

In [3]:
x=10
y=5
z=x-y
z

5

In [4]:
x=10
y=5
z=x*y
z

50

In [8]:
first_name="rezaul"
second_name="haque"
full_name=first_name*second_name
full_name

TypeError: can't multiply sequence by non-int of type 'str'

In [11]:
text="my age is "
age="22"
result=text+age
result

'my age is 22'

In [12]:
x=27
y=3
z=x//y
z

9

In [13]:
x=27
y=4
z=x//y
z

6

## floor division it eturn quetient ekse it returnt zero

### relational operator

In [14]:
x=25
y=30
x>y

False

In [15]:
x=25
y=30
x<y

True

In [16]:
x=25
y=30
x==y

False

In [17]:
x=25
y=30
x!=y

True

In [18]:
x=25
y=30
x>=y

False

In [19]:
x=25
y=30
x<=y

True

### logical operators

In [20]:
is_student=True
in_college=True
in_school=False

In [21]:
is_student and in_college

True

In [22]:
is_student and in_school

False

In [23]:
is_student or in_college

True

In [24]:
is_student or in_school

True

In [25]:
in_school or in_school

False

In [26]:
not(in_college)

False

### membership operator

In [28]:
vowels="aeiou"
print("u" in vowels)

True


In [29]:
### assignment operators

In [30]:
a=4
b=3
a=a+b
a

7

In [31]:
a=4
b=3
a+=b
a

7

In [32]:
a=4
b=3
a-=b
a

1

In [33]:
a=4
b=3
a*=b
a

12

In [34]:
a=4
b=3
a%=b
a

1

In [35]:
a=4
b=3
a**=b
a

64

## conditional statement

In [40]:
num=5
if(num>0):
    print(num,"is greater than zero")

5 is greater than zero


In [41]:
num=5
if(num<0):
    print(num,"is greater than zero")

In [49]:
age=int(input("enter age:"))
if(0<age<3):
    print("no fares for age group 0-3")
elif(3<age<10):
        print("bus fare is 10") 
elif(10<age<20):
        print("bus fare is 20")  
else:                       
     print("bus fare is 30")

enter age:20
bus fare is 30


## day 3

In [7]:
num1=10
num2=34
num3=5
if (num1>num2):
    print(num3,"is greater")
else:
     if (num3>num2):
            print(num)
else:
        print(num2,"is greater")

IndentationError: expected an indented block after 'if' statement on line 7 (2342934886.py, line 8)

In [12]:
user_id=input("enter user id:")
password=input("pssword:")
if (user_id=="ds_py"):
    if(password=="abc123"):
        print("password accepted.logged in")
    else:
        print("wrong password.please enter correct password")

enter user id:
pssword:


#### string

In [16]:
name="reza"
print(name)
type(name)

reza


str

In [17]:
text="i love python"

In [19]:
text[0]

'i'

In [20]:
text[:]

'i love python'

In [22]:
text[2]

'l'

In [23]:
text[-2]

'o'

In [24]:
text[2:6]

'love'

In [26]:
text[-1:6]

''

In [27]:
text[::-1]

'nohtyp evol i'

In [29]:
text[:len(text)]

'i love python'

In [30]:
text[2:12]

'love pytho'

In [31]:
text[2]

'l'

In [36]:
text[:-7:-1]

'nohtyp'

In [38]:
text[::-1]

'nohtyp evol i'

In [40]:
text[-3]

'h'

In [41]:
relace.("pythan","datascience)

SyntaxError: unterminated string literal (detected at line 1) (3944409851.py, line 1)

In [42]:
text.upper()

'I LOVE PYTHON'

In [43]:
text.lower()

'i love python'

In [44]:
text.title()

'I Love Python'

In [45]:
date="04","06","2023"
sep='-'
sep.join(date)

'04-06-2023'

In [46]:
text="***python*for*data*science***"
text.strip("*")

'python*for*data*science'

In [47]:
text="***python*for*data*science"
text.strip("*")

'python*for*data*science'

### list

In [49]:
sample_list=[1,2,3,4,5,-1,"hi",1,1,2]
sample_list

[1, 2, 3, 4, 5, -1, 'hi', 1, 1, 2]

In [50]:
type(sample_list)

list

### elemnet in a list are saperated byt comma and enclosed i square brackets

### list is hetrogenous>multiple data types

### list can have duplicates 

In [56]:
book_list=["python","r"]
print(book_list)
type(book_list)           

['python', 'r']


list

In [57]:
products=["dairy","bakery","grocery","clothing"]
print("bakery" in products)

True


In [60]:
print("bakery" not in products)

False


In [61]:
for books in products:
    print(books)

dairy
bakery
grocery
clothing


In [62]:
prices=[1,2,3,4,5,-1]
len(prices)

6

In [63]:
max(prices)

5

In [64]:
min(prices)

-1

In [65]:
products.clear()

In [66]:
products

[]

In [67]:
prices=[1,2,3,4,5,-1,1,1,1,1,1]
prices.count(1)

6

In [68]:
items=["hi","hello"]
prices.extend(items)

In [69]:
prices

[1, 2, 3, 4, 5, -1, 1, 1, 1, 1, 1, 'hi', 'hello']

In [70]:
prices.index("hi")

11

In [71]:
prices.insert(2,"ai")
prices

[1, 2, 'ai', 3, 4, 5, -1, 1, 1, 1, 1, 1, 'hi', 'hello']

In [76]:
prices.pop(2)
prices

[1, 2, 4, 5, -1, 1, 1, 1, 1, 1, 'hi', 'hello']

In [77]:
prices.remove("hello")

In [78]:
prices

[1, 2, 4, 5, -1, 1, 1, 1, 1, 1, 'hi']

In [79]:
prices[0:3]

[1, 2, 4]

In [80]:
prices[3:7]

[5, -1, 1, 1]

In [81]:
prices[-1]

'hi'

In [82]:
prices[0:-1]

[1, 2, 4, 5, -1, 1, 1, 1, 1, 1]

In [83]:
prices[0]="ds"

In [84]:
prices

['ds', 2, 4, 5, -1, 1, 1, 1, 1, 1, 'hi']

In [ ]:
#### list is muteable change with 

#### day 4

### tuple

#### 1) container object
#### 2) heterogenous ->allows multiple data type
#### 3) can have duplicates
#### 4) immutable
#### 5) element are separated by comma,enclosed in parenthesis or without any brackets

In [1]:
num=10
addition=0
i=0
while(i<=num):
    addition=addition+i
    i=i+1
print("addition is:",addition)

addition is: 55


In [3]:
number=range(1,11)
addition=0
for i in number:
    addition=addition+i
print("addition is:",addition)

addition is: 55


In [5]:
text="knowledgehut"
for letter in text:
    if letter =='h':
        break
    print(letter)
print("the for loop executing")

k
n
o
w
l
e
d
g
e
the for loop executing


In [7]:
text="knowledge hut"
for letter in text:
    if letter == ' ':
        print("the loop skipped a space here")
        continue 
    print(letter)

k
n
o
w
l
e
d
g
e
the loop skipped a space here
h
u
t


In [11]:
levels = int(input("enter number of levels: "))
for level in range(1, levels+1):
    for num in range(level):
        print(level,end=" ")
        
    print("\n")

enter number of levels: 5
1 

2 2 

3 3 3 

4 4 4 4 

5 5 5 5 5 



## numpy:package for multidimensional array

In [14]:
import numpy as np

In [5]:
simple_list=[7,8,9]
np.array(simple_list)

array([7, 8, 9])

In [6]:
arr=np.array([3,4,5])
arr

array([3, 4, 5])

In [7]:
list_of_lists=[[2,3,4],[5,6,7,],[8,9,10]]
np.array(list_of_lists)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [8]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [9]:
np.arange(1,20,4) # shift+tab> help box

array([ 1,  5,  9, 13, 17])

In [10]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.ones(40)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [15]:
np.ones(6,int)

array([1, 1, 1, 1, 1, 1])

In [16]:
np.zeros((3,6),int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [18]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
np.ones((3,6),int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [21]:
np.linspace(0,5,8)

array([0.        , 0.71428571, 1.42857143, 2.14285714, 2.85714286,
       3.57142857, 4.28571429, 5.        ])

In [15]:
np.linspace(0,30,50 )

array([ 0.        ,  0.6122449 ,  1.2244898 ,  1.83673469,  2.44897959,
        3.06122449,  3.67346939,  4.28571429,  4.89795918,  5.51020408,
        6.12244898,  6.73469388,  7.34693878,  7.95918367,  8.57142857,
        9.18367347,  9.79591837, 10.40816327, 11.02040816, 11.63265306,
       12.24489796, 12.85714286, 13.46938776, 14.08163265, 14.69387755,
       15.30612245, 15.91836735, 16.53061224, 17.14285714, 17.75510204,
       18.36734694, 18.97959184, 19.59183673, 20.20408163, 20.81632653,
       21.42857143, 22.04081633, 22.65306122, 23.26530612, 23.87755102,
       24.48979592, 25.10204082, 25.71428571, 26.32653061, 26.93877551,
       27.55102041, 28.16326531, 28.7755102 , 29.3877551 , 30.        ])

In [17]:
np.eye((16))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [25]:
np.random.rand(4,5)

array([[0.5123639 , 0.20381237, 0.10826165, 0.87759459, 0.15133407],
       [0.13952962, 0.3225398 , 0.96416366, 0.01517859, 0.0094376 ],
       [0.22878336, 0.9312927 , 0.42218924, 0.23672763, 0.83540318],
       [0.46905719, 0.21439058, 0.04956988, 0.72170134, 0.44157939]])

In [27]:
arr=np.random.randn(4,5)
arr

array([[-0.90036714, -0.98891577,  2.35839113, -0.5675674 , -0.49333329],
       [ 0.07444784,  0.36036853,  1.35845941,  1.0730894 ,  0.16243471],
       [ 1.36460563,  0.19333007, -0.43822485, -0.26111807,  1.3103736 ],
       [-1.55547062, -0.67431905, -0.09928839,  2.27229426, -1.09103192]])

In [30]:
np.random.randint(3,60)

45

In [32]:
np.random.randint(20,60,100)

array([37, 47, 28, 29, 30, 36, 20, 59, 58, 33, 46, 34, 28, 42, 56, 33, 29,
       51, 38, 58, 20, 35, 54, 20, 33, 59, 46, 34, 25, 48, 23, 56, 37, 30,
       54, 36, 31, 27, 43, 27, 58, 56, 46, 55, 42, 44, 59, 59, 58, 21, 44,
       48, 29, 50, 42, 56, 38, 55, 46, 45, 30, 39, 48, 59, 31, 42, 32, 57,
       47, 50, 47, 50, 25, 20, 47, 58, 20, 36, 25, 39, 51, 52, 30, 37, 56,
       53, 40, 45, 53, 50, 29, 55, 34, 33, 31, 28, 23, 49, 25, 29])

In [40]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
rand_array=np.random.randint(0,100,20)
rand_array

array([ 3, 91,  6, 80, 97, 76, 45, 90, 50, 22, 78, 39, 89, 47, 79, 53, 40,
       46, 95, 70])

In [38]:
sample_array.reshape(5,6)

NameError: name 'sample_array' is not defined

In [39]:
sample_array.reshape(5.6)
sample_array

NameError: name 'sample_array' is not defined

In [22]:
rand_array.max()

97

In [26]:
rand_array.argmax()

4

In [30]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
a=np.random.rand(3,6)
a

array([[0.64845547, 0.56135575, 0.07592865, 0.54297635, 0.37163563,
        0.6702901 ],
       [0.54656349, 0.15958245, 0.78663043, 0.83063864, 0.30886684,
        0.49169728],
       [0.66387601, 0.5423946 , 0.44719857, 0.1148443 , 0.95685738,
        0.32852432]])

In [34]:
a.T

array([[0.64845547, 0.54656349, 0.66387601],
       [0.56135575, 0.15958245, 0.5423946 ],
       [0.07592865, 0.78663043, 0.44719857],
       [0.54297635, 0.83063864, 0.1148443 ],
       [0.37163563, 0.30886684, 0.95685738],
       [0.6702901 , 0.49169728, 0.32852432]])

In [41]:
sample_array=np.arange(5,15)
sample_array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
sample_array[3]

8

In [45]:
sample_array[0:4]

array([5, 6, 7, 8])

In [47]:
sample_array[2:5]=100
sample_array

array([  5,   6, 100, 100, 100,  10,  11,  12,  13,  14])

In [50]:
sample_array=np.arange(30,40)
sample_array

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [51]:
sample_array[0:6]

array([30, 31, 32, 33, 34, 35])

In [54]:
subset_sample_array=sample_array[0:3]
subset_sample_array

array([30, 31, 32])

In [56]:
subset_sample_array[:]=100
subset_sample_array

array([100, 100, 100])

# two-dimentional array

In [57]:
sample_matrix=np.array(([10,20,39],[40,50,60],[70,80,90]))
sample_matrix

array([[10, 20, 39],
       [40, 50, 60],
       [70, 80, 90]])

In [58]:
sample_matrix[1,2]

60

In [59]:
sample_matrix[1,:]

array([40, 50, 60])

In [61]:
sample_matrix[:,0]

array([10, 40, 70])

In [62]:
sample_matrix[2]

array([70, 80, 90])

In [64]:
sample_matrix[:,(0,2)]

array([[10, 39],
       [40, 60],
       [70, 90]])

# selection techniques

In [67]:
sample_array=np.arange(20,30)

In [68]:
sample_array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
sample_array+sample_array

array([40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [71]:
np.exp(sample_array)

array([4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
       1.44625706e+12, 3.93133430e+12])

In [72]:
np.sqrt(sample_array)

array([4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])

In [75]:
np.log(sample_array)

array([2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583])

In [76]:
np.max(sample_array)

29

In [77]:
np.min(sample_array)

20

In [78]:
np.argmax(sample_array)

9

In [79]:
np.argmin(sample_array)

0

In [80]:
np.square(sample_array)

array([400, 441, 484, 529, 576, 625, 676, 729, 784, 841])

In [81]:
np.std(sample_array)

2.8722813232690143

In [83]:
np.var(sample_array)

8.25

In [84]:
np.mean(sample_array)

24.5

In [87]:
array=np.random.randn(3,4)
array

array([[ 1.96683067, -0.76805585, -1.74553669, -1.44760383],
       [ 0.2981373 , -2.17569759,  1.2764315 ,  0.21885039],
       [ 2.08798254,  1.26369132, -0.33157949, -1.61884001]])

In [88]:
np.round(array,decimals=2)

array([[ 1.97, -0.77, -1.75, -1.45],
       [ 0.3 , -2.18,  1.28,  0.22],
       [ 2.09,  1.26, -0.33, -1.62]])

In [89]:
sports=np.array(["golf","cricket","football"])
np.unique(sports)

array(['cricket', 'football', 'golf'], dtype='<U8')